issues/urls.py
from django.urls import path
from .views import home, IssueCreateView, IssueDetailView, IssueListView, IssueUpdateView, IssueDeleteView

urlpatterns = [
  path('', home, name='home'),
  # path('issues/', list_view,name='issues'),
  # path('issues/create', create_view, name='create')
  path('issues/', IssueListView.as_view(), name='issues'),
  path('issues/create', IssueCreateView.as_view(), name='issue_create'),
  path('issues/<int:pk>', IssueDetailView.as_view(), name='issue_detail'),
  path('issues/<int:pk>/edit', IssueUpdateView.as_view(), name='issue_edit'),
  path('issues/<int:pk>/delete', IssueDeleteView.as_view(), name='issue_delete')
]

main_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('issues.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from .views import users

urlpatterns = [
    path('', users, name='users'),
    path('', include('django.contrib.auth.urls'))
]

issues/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Issue(models.Model):
    issue_name = models.CharField(max_length=200)
    body = models.TextField()
    created_by = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    date_created = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.issue_name

    def get_absolute_url(self):
        return reverse("issue_detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models

# Create your models here.

issues/forms.py
from socket import fromshare
from django import forms
from .models import Issue

class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['issue_name', 'body', 'created_by']

issues/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Issue
from .forms import IssueForm
from django.urls import reverse_lazy

# Create your views here.
def home(request):
    context = {}
    return render(request, 'home.html', context)

class IssueListView(ListView):
    model = Issue
    template_name = 'issues.html'

class IssueDetailView(DetailView):
    model = Issue
    template_name = 'issue_detail.html'

class IssueCreateView(CreateView):
    model = Issue
    template_name = 'issue_create.html'
    fields = ['issue_name', 'body', 'created_by']

class IssueUpdateView(UpdateView):
    model = Issue
    template_name = 'issue_edit.html'
    fields = ['issue_name', 'body']

class IssueDeleteView(DeleteView):
    model = Issue
    template_name = 'issue_delete.html'
    success_url = reverse_lazy('issues')

# def list_view(request):
#     # dictionary for initial data with
#     # field names as keys
#     context ={}

#     # add the dictionary during initialization
#     context["dataset"] = Issue.objects.all()
            
#     return render(request, "issues.html", context)

# def create_view(request):
#     context = {}

#     form = IssueForm(request.POST or None)
#     if form.is_valid():
#         form.save()

#     context['form'] = form

#     return render(request, "create_issue.html", context)

users/views.py
from django.shortcuts import render

# Create your views here.
def users(request):
    context = {}
    return render(request, 'users.html', context=context)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Issue Tracker</title>
</head>

<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Issue Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users' %}">User Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'issues' %}">Issues</a>
                    </li>
                </ul>
                <form class="d-lg-flex justify-content-end align-items-center" role="search">
                    {% if user.is_authenticated %}
                    <a class="nav-link me-3" href="{% url 'users' %}">Hello, {{ request.user }}!</a>
                    <a href="{% url 'logout' %}" class="btn btn-outline-danger" type="submit">Log Out</a>
                    {% else %}
                    <a class="nav-link me-3" href="{% url 'users' %}">You are not logged in</a>
                    <a href="{% url 'login' %}" class="btn btn-outline-success" type="submit">Log in</a>
                    {% endif %}
                </form>
            </div>
        </div>
    </nav>

    <!-- navbar -->

    <div class="container mt-2">
        {% block content %}
        {% endblock content %}
    </div>


    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>

</html>

templates/create_issue.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'create' %}" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="submit">
</form>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="h-100 p-5 bg-light border rounded-3">
    <h2 class="display-5 fw-bold">Home</h2>
    <p>This page will show the graphs of the issues and projects that belong to the user</p>
    <p>or if not log in, it will be a page that shows the description of the app.</p>
    <button class="btn btn-outline-secondary" type="button">Example button</button>
</div>
{% endblock content %}

templates/issue_create.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="submit">
</form>

{% endblock %}

templates/issue_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Post</h1>

<form method="POST">
    {% csrf_token %}

    <p>Are you sure you want to delete "{{ issue.issue_name }}?"</p>
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

templates/issue_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card mt-2">
    <h3 class="card-header bg-dark text-bg-primary">{{ issue.id }} | {{ issue.issue_name }}</h5>
    <div class="card-body">
        <h5 class="card-title">{{ issue.body }}</h5>
        <p class="card-text">Author: {{ issue.created_by }}</p>
        <p class="card-text">Created: {{ issue.date_created }} | Updated: {{ issue.date_updated }}</p>
        <a href="{% url 'issues' %}" class="btn btn-primary">Back to Issues</a>
    </div>
</div>
{% endblock content %}

templates/issue_edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit issue</h1>
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Update">
</form>
{% endblock content %}

templates/issues.html
{% extends 'base.html' %}

{% block content %}
<a class="btn btn-primary" href="{% url 'issue_create' %}">+ New Issue</a>
<hr class="my-4">
{% for issue in issue_list %}
<div class="card mt-2">
    <h5 class="card-header bg-dark text-bg-primary">{{ issue.id }} | <a href="{% url 'issue_detail' issue.id %}">{{ issue.issue_name }}</a></h5>
    <div class="card-body">
        <h5 class="card-title">{{ issue.body }}</h5>
        <a href="{% url 'issue_edit' issue.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'issue_delete' issue.id %}" class="btn btn-danger">Delete</a>
    </div>
</div>
{% endfor %}
{% endblock content %}

templates/users.html
{% extends 'base.html' %}

{% block content %}


<h1>Users</h1>

{% endblock content %}